blog/urls.py
from django.views.decorators.cache import cache_page

from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView
from mailing.apps import MailingConfig

from django.urls import path


app_name = MailingConfig.name

urlpatterns = [
    path('blog_list/', BlogListView.as_view(), name='blog_list'),  # Список постов блога. Могут смотреть все
    path('create_blog/', BlogCreateView.as_view(), name='create_blog'),  # Создание блога, доступно контент менеджеру
    path('blog_detail/<slug:slug>', cache_page(100)(BlogDetailView.as_view()), name='blog_view'),  # Пост Виден всем
    path('blog_edit/<slug:slug>', BlogUpdateView.as_view(), name='blog_edit'),  # Изменение поста. доступно только КМ
    path('blog_delete/<slug:slug>', BlogDeleteView.as_view(), name='blog_delete'),  # Удаление поста. доступно только КМ
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailin')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from mailing.apps import MailingConfig
from django.urls import path
from mailing.views import MailinListView, MailinCreateView, MailinDetailView, MailinDeleteView, MailinUpdateView, \
    ClientDetailView, ClientUpdateView, ClientCreateView, ClientListView, AttemptsLogListView, MessageCreateView, \
    MessageUpdateView, MessageDeleteView, MailinManagerUpdateView, UserListView, UserUpdateView, home_page

app_name = MailingConfig.name

urlpatterns = [
    path('', MailinListView.as_view(), name='mailing_list'),  # Список всех рассылок пользователя
    path('create_mailing/', MailinCreateView.as_view(), name='create_mailing'),  # Создание рассылки
    path('detail_mailing/<slug:slug>/', MailinDetailView.as_view(), name='detail_mailing'),  # Просмотр рассылки
    path('delete_mailing/<slug:slug>/', MailinDeleteView.as_view(), name='delete_mailing'),  # Удаление рассылки
    path('update_mailing/<slug:slug>/', MailinUpdateView.as_view(), name='update_mailing'),  # Обновление рассылки

    path('detail_client/<int:pk>/', ClientDetailView.as_view(), name='detail_client'),  # Просмотр клиента
    path('update_client/<int:pk>/', ClientUpdateView.as_view(), name='update_client'),  # Изменение клиента
    path('create_client/', ClientCreateView.as_view(), name='create_client'),  # Создание клиента
    path('client_list/', ClientListView.as_view(), name='client_list'),  # Список клиентов пользователя

    path('log_list/', AttemptsLogListView.as_view(), name='log_list'),  # Лог об отправке сообщений на почту

    path('create_message/', MessageCreateView.as_view(), name='create_message'),  # Создание сообщения для рассылки
    path('update_message/<int:pk>/', MessageUpdateView.as_view(), name='update_message'),  # Изменения сообщения
    path('delete_message/<int:pk>/', MessageDeleteView.as_view(), name='delete_message'),  # Удаление сообщения

    # Обновление рассылки для менеджер
    path('manager_update_mailing/<slug:slug>/', MailinManagerUpdateView.as_view(), name='manager_update_mailing'),
    path('user_list', UserListView.as_view(), name='user_list'),  # Список пользователей для менеджер
    path('update_user/<int:pk>/', UserUpdateView.as_view(), name='update_user'),  # Изменение пользователя для менеджера

    path('home_page/', home_page, name='home_page'),  # Домашняя страница с 3 статьями из блога и статистикой
]

users/urls.py
from django.urls import path
from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, verify_view, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView

app_name = UsersConfig.name

urlpatterns = [
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verifying/', verify_view, name='verify_view'),  # эндпоинт верификации почты

    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Email')

    phone = models.CharField(max_length=20, verbose_name='номер телефона', **NULLABLE)
    country = models.CharField(max_length=58, verbose_name='название страны', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)

    verified = models.BooleanField(default=False, verbose_name='верифицирован', blank=True)
    verified_password = models.IntegerField(verbose_name='ключ для верификации')

    telegram = models.URLField(verbose_name='ссылка на телеграмм (для уведомлений)', **NULLABLE, max_length=200)
    telegram_id = models.CharField(verbose_name='id телеграмма', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

mailing/forms.py
from django import forms
from django.contrib.admin import widgets
from mailing.models import Client, Mailin


class MailinCreateForm(forms.ModelForm):

    clients = forms.ModelMultipleChoiceField(queryset=Client.objects.all(), required=False)  # подтягивает клиентов
    start_time = forms.SplitDateTimeField(widget=widgets.AdminSplitDateTime)
    finish_time = forms.SplitDateTimeField(widget=widgets.AdminSplitDateTime)

    class Meta:
        model = Mailin
        fields = ('name', 'start_time', 'finish_time', 'interval', 'clients',)


class MailinUpdateForm(forms.ModelForm):

    clients = forms.ModelMultipleChoiceField(queryset=Client.objects.all(), required=False)  # подтягивает клиентов
    start_time = forms.DateTimeField()
    finish_time = forms.DateTimeField()

    class Meta:
        model = Mailin
        fields = ('name', 'start_time', 'finish_time', 'interval', 'clients', 'message')

users/forms.py
from django.contrib.auth.forms import UserCreationForm

from users.models import User


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2', 'telegram')

mailing/views.py
from django.contrib.auth.models import AnonymousUser
from django.core.cache import cache
from django.shortcuts import render
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from config import settings
from users.models import User
from .forms import MailinCreateForm, MailinUpdateForm
from mailing.models import AttemptsLog, Message
from django.urls import reverse_lazy, reverse
from .models import Mailin, Client
from .services import get_three_articles


# Create your views here.


class MailinListView(LoginRequiredMixin, ListView):
    model = Mailin

    def get_queryset(self):
        user = self.request.user
        if isinstance(user, AnonymousUser):  # Проверяет анонимный ли юзер. Если да, ничего не показывает
            return Mailin.objects.none()
        elif user.groups.filter(name='manager').exists():  # Менеджеру показывает все рассылки
            return super().get_queryset()
        return Mailin.objects.filter(owner=user)  # Для каждого обычного пользователя показывает только его рассылки


class MailinCreateView(LoginRequiredMixin, CreateView):
    model = Mailin
    success_url = reverse_lazy('mailin:mailing_list')  # Адрес для перенаправления после успешного создания

    def form_valid(self, form):
        user = self.request.user  # Получает текущего пользователя, который отправил форму
        self.object = form.save()
        self.object.owner = user  # Сохраняет автора
        self.object.save()

        return super().form_valid(form)

    def get_form_class(self):  # Предлагает только клиентов, которых создал пользователь\
        model_form = MailinCreateForm
        model_form.base_fields['clients'].limit_choices_to = {'owner': self.request.user}
        return model_form


class MailinDetailView(LoginRequiredMixin, DetailView):
    model = Mailin

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mailin = self.object
        clients = Client.objects.filter(mailin=mailin)  # Показывает только клиентов этой рассылки
        context['list_clients'] = clients
        return context


class MailinDeleteView(LoginRequiredMixin, DeleteView):
    model = Mailin  # Модель
    success_url = reverse_lazy('mailin:mailing_list')


class MailinUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailin  # Модель

    # Тут нужно получить только клиентов этого пользователя
    form_class = MailinUpdateForm
    success_url = reverse_lazy('mailin:mailing_list')  # Адрес для перенаправления после успешного редактирования

    def get_form_class(self):  # Предлагает только клиентов, которых создал пользователь
        model_form = MailinUpdateForm
        # Следит за тем чтобы предложены только клиенты и сообщения созданные этим пользователем
        model_form.base_fields['clients'].limit_choices_to = {'owner': self.request.user}
        model_form.base_fields['message'].limit_choices_to = {'owner': self.request.user}

        return model_form

    def form_valid(self, form):
        # Сохраняет рассылку
        mailin = form.save()

        # Получает клиентов, связанных с этой рассылкой
        clients = form.cleaned_data['clients']

        # Проходим по всем клиентам и добавляет в поле mailin эту рассылку
        for client in clients:
            client.mailin.add(mailin)
            client.save()
        return super().form_valid(form)


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    fields = ('name', 'comment', 'email', 'mailin')

    def get_success_url(self):
        return reverse('mailin:detail_client', args=[self.kwargs.get('pk')])


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    fields = ('name', 'comment', 'email', 'mailin')

    def get_form_class(self):
        model_form = super().get_form_class()  # Дает выбирать только сообщения созданные пользователем
        model_form.base_fields['mailin'].limit_choices_to = {'owner': self.request.user}
        return model_form

    def form_valid(self, form):  # Присваивает только что созданного клиента пользователю
        user = self.request.user
        instance = form.save(commit=False)
        instance.owner = user
        instance.save()
        form.save_m2m()  # Сохранят связи ManyToMany
        return super().form_valid(form)

    success_url = reverse_lazy('mailin:mailing_list')


class ClientListView(ListView):
    model = Client

    def get_queryset(self):
        user = self.request.user
        if isinstance(user, AnonymousUser):  # Если не авторизирован, клиентов не показывает
            return Client.objects.none()
        return Client.objects.filter(owner=user)  # Показывает клиентов только созданных пользователем


class AttemptsLogListView(ListView):
    model = AttemptsLog


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    fields = ('name', 'text',)

    def form_valid(self, form):  # Присваивает только что созданного клиента пользователю
        user = self.request.user
        instance = form.save(commit=False)
        instance.owner = user
        instance.save()
        form.save_m2m()  # Сохранят связи ManyToMany
        return super().form_valid(form)

    success_url = reverse_lazy('mailin:mailing_list')  # Адрес для перенаправления после успешного редактирования


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    fields = ('name', 'text',)
    success_url = reverse_lazy('mailin:mailing_list')  # Адрес для перенаправления после успешного редактирования


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message  # Модель
    success_url = reverse_lazy('mailin:mailing_list')


class ManagerPassesTestMixin(UserPassesTestMixin):
    """
    Проверяет, что этот пользователь менеджер. Если да, разрешает доступ
    """
    def test_func(self):
        return self.request.user.groups.filter(name='manager').exists()


class MailinManagerUpdateView(ManagerPassesTestMixin, UpdateView):
    """
    Страница для менеджера, на которой он может только менять статус рассылки
    """
    model = Mailin
    fields = ('status',)
    success_url = '/'


class UserListView(ManagerPassesTestMixin, ListView):
    """
    Страница для менеджера, на которой он может выбрать пользователя
    """
    model = User
    template_name = 'mailing/user_list.html'


class UserUpdateView(ManagerPassesTestMixin, UpdateView):
    """
    Страница для менеджера, на которой он может заблокировать или разблокировать пользователя
    """
    model = User
    fields = ('is_active',)
    success_url = '/user_list'
    template_name = 'mailing/user_form.html'


def home_page(request):
    """
    Домашняя страница
    """
    if settings.CACHE_ENABLED:
        key = 'first_three_articles'
        first_three_articles = cache.get(key)

        if first_three_articles is None:
            first_three_articles = get_three_articles()
            cache.set(key, first_three_articles)  # Кэширует рассылки

    else:
        first_three_articles = get_three_articles()

    context = {
        'all_mailing_num': Mailin.objects.count(),  # Количество всех рассылок
        'active_mailing_num': Mailin.objects.filter(status='active').count(),  # Количество активных рассылок
        'clients_num': Client.objects.count(),  # Количество клиентов
        'articles': first_three_articles  # Статьи из блога
    }

    return render(request, 'mailing/home_page.html', context)

users/views.py
from random import randint
from django.contrib.auth.views import (PasswordResetDoneView as BasePasswordResetDoneView,
                                       PasswordResetView as BasePasswordResetView,
                                       PasswordResetConfirmView as BasePasswordResetConfirmView,
                                       PasswordResetCompleteView as BasePasswordResetCompleteView)
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.contrib.auth.views import LoginView as BaseLoginView
from django.core.mail import send_mail
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy

from config import settings
from users.forms import UserForm
from users.models import User


# Create your views here.

class LoginView(BaseLoginView):
    template_name = 'users/login.html'


class LogoutView(BaseLogoutView):
    pass


class RegisterView(CreateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/register.html'

    def form_valid(self, form):

        # создает случайный пароль
        verified_password = ''
        for i in range(8):
            i = randint(0, 9)
            verified_password += str(i)

        # сохраняет пароль к пользователю, чтобы можно было авторизировать его
        form.verified_password = verified_password
        user = form.save(commit=False)
        user.verified_password = verified_password

        # Отправляет письмо на указанную почту со ссылкой. В ссылку встроен пароль для верификации этого пользователя
        send_mail(
            subject='Верификация почты',
            message=f'Если вы регистрировались в Skychimp, нажмите на ссылку: '
                    f'http://127.0.0.1:8000/users/verifying?code={user.verified_password}\n Так вы подтвердите почту',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        return super().form_valid(form)


def verify_view(request):
    code = int(request.GET.get('code'))  # получает код для верификации
    user = User.objects.get(verified_password=code)  # получает пользователя с этим кодом
    user.verified = True  # верифицирует его
    user.save()
    return render(request, 'users/verifying.html')


class PasswordResetView(BasePasswordResetView):
    template_name = 'users/password_reset_form.html'
    email_template_name = 'users/password_reset_email.html'
    from_email = settings.EMAIL_HOST_USER
    success_url = reverse_lazy('users:password_reset_done')


class PasswordResetDoneView(BasePasswordResetDoneView):
    template_name = 'users/password_reset_done.html'


class PasswordResetConfirmView(BasePasswordResetConfirmView):
    template_name = 'users/password_reset_confirm.html'
    success_url = reverse_lazy('users:password_reset_complete')


class PasswordResetCompleteView(BasePasswordResetCompleteView):
    template_name = 'users/password_reset_complete.html'
    success_url = reverse_lazy('users:login')

mailing/templates/mailing/attemptslog_list.html
{% extends 'mailing/base.html' %}
{% block content %}

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">Отчеты по рассылкам</h1>
          <p>В этом разделе можно посмотреть историю отправки сообщений.<p>
        </div>
      </div>
      <div class="container">
        {% for object in object_list %}
          <div class="row">
            <div class="col-md-4">
              <h2>Время отправки: "{{ object.last_time }}"</h2>
              {% if object.status %}
                  <p>Статус: успешно</p>
              {% else %}
                  <p>Статус: не отправлено</p>
              {% endif %}
            </div>
          </div>
          <hr>
        {% endfor %}
      </div> <!-- /container -->

{% endblock %}

mailing/templates/mailing/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Skychimp</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/jumbotron/">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/jumbotron.css' %}" rel="stylesheet">
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="/home_page/">Домашняя страница</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Рассылки <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/client_list">Клиенты</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/log_list">Мониторинг</a>
          </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:blog_list' %}">Перейти к нашему блогу</a>
          </li>
            {% if user.is_staff %}
              <li class="nav-item">
              <a class="nav-link" href="/user_list">Перейти к пользователям</a>
              </li>
            {% endif %}

          {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Добавить</a>
              <div class="dropdown-menu" aria-labelledby="dropdown01">
                <a class="dropdown-item" href="/create_mailing">Рассылку</a>
                <a class="dropdown-item" href="/create_client">Клиента</a>
                <a class="dropdown-item" href="/create_message">Сообщение</a>
              </div>
            </li>
          {% endif %}
        </ul>
        <div class="col=4"></div>

        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            {% if user.is_staff %}
              <a class="text-muted" href="{% url 'blog:create_blog' %}">Написать новый блог</a>
              <div class="col=1"></div>
            {% endif %}

            {% if not user.telegram %}
              <a class="text-muted" href="https://t.me/DispatchNotifierBot" target="_blank">Привязать Telegram</a>
              <div class="col=1"></div>
            {% endif %}

            {% if user.is_authenticated %}
              <a class="text-muted" href="{% url 'users:logout' %}">Выйти ({{request.user}})</a>
            {% else %}
              <a class="text-muted" href="{% url 'users:login' %}">Войти</a>
              <div class="col=1"></div>
              <a class="text-muted" href="{% url 'users:register' %}">Зарегистрироваться</a>
              <div class="col=1"></div>
            {% endif %}
          </li>

        </ul>

      </div>
    </nav>

    <main role="main">
      {% block content %}
      {% endblock %}
    </main>

    <footer class="container">
      <p>&copy; Skychimp 2023</p>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="{% static 'js/vendor/jquery-slim.min.js' %}"><\/script>')</script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

mailing/templates/mailing/client_detail.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
          <div class="col-md-4">
            <h2>ФИО: "{{ object.name|title }}"</h2>
            <p>Электронная почта: {{ object.email }}</p>
            <p>Комментарий: {{ object.comment }}</p>
            <hr>

            <p>Подписки:</p>
              {% for mailin in object.mailin.all %}
                <p>{{ mailin }}</p>
              {% endfor %}
          </div>
        </div>
        <hr>

        <p><a class="btn btn-secondary" href="{% url 'mailing:update_client' object.pk %}" role="button">Изменить &raquo;</a></p>

    </div>

{% endblock %}

mailing/templates/mailing/client_form.html
{% extends 'mailing/base.html' %}
{% block content %}


  <body class="bg-light">

    <div class="container">
      <div class="py-5 text-center">
        <img class="d-block mx-auto mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
        <h2>Клиент</h2>
        <p class="lead">Заполните необходимые поля.</p>
      </div>

      <div class="row">

        <div class="col-md-8 order-md-1">
          <h4 class="mb-3">Поля:</h4>
          <form class="needs-validation" method="post">
            <div class="row">
              <div class="col-md-6 mb-3">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-primary btn-lg btn-block" type="submit">Подтвердить</button>
              </div>
            </div>



            <hr class="mb-4">
          </form>
        </div>
      </div>

      <footer class="my-5 pt-5 text-muted text-center text-small">
        <ul class="list-inline">
          {% if object %}
            <li class="list-inline-item"><a href="{% url 'mailing:detail_client' object.pk %}">Отмена</a></li>
          {% else %}
            <li class="list-inline-item"><a href="/">Отмена</a></li>
          {% endif %}
        </ul>
      </footer>
    </div>

{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html' %}
{% block content %}

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">Список клиентов</h1>
            {% if user.is_authenticated %}
                <p>В этом разделе вы можете посмотреть список клиентов или добавить нового.<p>
                <a class="btn btn-primary btn-lg" href="/create_client" role="button">Добавить клиента &raquo;</a></p>
            {% else %}
                <p>В этом разделе вы увидите список своих клиентов после авторизации<p>
            {% endif %}
        </div>
      </div>
      <div class="container">
        {% for object in object_list %}
          <div class="row">
            <div class="col-md-4">
              <h2>ФИО: "{{ object.name|title }}"</h2>
              <p>Почта: {{object.email}}</p>
              <p>Информация: {{object.comment}}</p>
              <p><a class="btn btn-secondary" href="{% url 'mailing:detail_client' object.pk %}" role="button">Детали &raquo;</a></p>
            </div>
          </div>
          <hr>
        {% endfor %}
      </div> <!-- /container -->

{% endblock %}

mailing/templates/mailing/home_page.html
{% extends 'mailing/base.html' %}
{% block content %}

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">Добро пожаловать на Skychimp</h1>
              <p>Нам доверили уже {{ all_mailing_num }} рассылок!<p>
              <p>А в активном режиме находится {{ active_mailing_num }}!<p>
              <a class="btn btn-primary btn-lg" href="create_mailing" role="button">Добавить рассылку &raquo;</a></p>
        </div>
      </div>
      <div class="container">
        {% for object in articles %}
            {% include 'includs/inc_blog.html' %}
        {% endfor %}
      </div> <!-- /container -->

{% endblock %}

mailing/templates/mailing/mailin_confirm_delete.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="jumbotron">
    <div class="container">
      <h1 class="display-3">Удалить рассылку "{{object.name}}"</h1>
      <p>Рассылку нельзя будет восстановить. Вместе с ней будут удалены и сообщения и история отправок</p>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <button role="submit" class="btn btn-danger">Удалить &raquo;</button>
                <a class="btn btn-primary btn-lg" href="/" role="button">Отменить удаление &raquo;</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailin_form.html
{% extends 'mailing/base.html' %}
{% block content %}


  <body class="bg-light">

    <div class="container">
      <div class="py-5 text-center">
        <img class="d-block mx-auto mb-4" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
        <h2>Добавление рассылки</h2>
        <p class="lead">Заполните необходимые поля.</p>
      </div>

      <div class="row">

        <div class="col-md-8 order-md-1">
          <h4 class="mb-3">Поля:</h4>
          <form class="needs-validation" method="post">
            <div class="row">
              <div class="col-md-6 mb-3">
                {% csrf_token %}
                {{ form.as_p }}

                <button class="btn btn-primary btn-lg btn-block" type="submit">Подтвердить</button>
              </div>
            </div>



            <hr class="mb-4">
          </form>
        </div>
      </div>

      <footer class="my-5 pt-5 text-muted text-center text-small">
        <ul class="list-inline">
          <li class="list-inline-item"><a href="/">Обратно к рассылкам</a></li>
        </ul>
      </footer>
    </div>

{% endblock %}

mailing/templates/mailing/message_confirm_delete.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="jumbotron">
    <div class="container">
      <h1 class="display-3">Удалить сообщения "{{object.name}}"</h1>
      <p>Сообщение нельзя будет восстановить.</p>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <div class="btn-group" role="group">
                    <button role="submit" class="btn btn-danger">Удалить &raquo;</button>
                    <a class="btn btn-primary btn-lg" href="/" role="button">Отменить удаление &raquo;</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}