blog/urls.py
from django.views.decorators.cache import cache_page

from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView
from mailing.apps import MailingConfig

from django.urls import path


app_name = MailingConfig.name

urlpatterns = [
    path('blog_list/', BlogListView.as_view(), name='blog_list'),  # Список постов блога. Могут смотреть все
    path('create_blog/', BlogCreateView.as_view(), name='create_blog'),  # Создание блога, доступно контент менеджеру
    path('blog_detail/<slug:slug>', cache_page(100)(BlogDetailView.as_view()), name='blog_view'),  # Пост Виден всем
    path('blog_edit/<slug:slug>', BlogUpdateView.as_view(), name='blog_edit'),  # Изменение поста. доступно только КМ
    path('blog_delete/<slug:slug>', BlogDeleteView.as_view(), name='blog_delete'),  # Удаление поста. доступно только КМ
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailin')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, verify_view, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView

app_name = UsersConfig.name

urlpatterns = [
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verifying/', verify_view, name='verify_view'),  # эндпоинт верификации почты

    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Email')

    phone = models.CharField(max_length=20, verbose_name='номер телефона', **NULLABLE)
    country = models.CharField(max_length=58, verbose_name='название страны', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)

    verified = models.BooleanField(default=False, verbose_name='верифицирован', blank=True)
    verified_password = models.IntegerField(verbose_name='ключ для верификации')

    telegram = models.URLField(verbose_name='ссылка на телеграмм (для уведомлений)', **NULLABLE, max_length=200)
    telegram_id = models.CharField(verbose_name='id телеграмма', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm

from users.models import User


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2', 'telegram')

users/views.py
from random import randint
from django.contrib.auth.views import (PasswordResetDoneView as BasePasswordResetDoneView,
                                       PasswordResetView as BasePasswordResetView,
                                       PasswordResetConfirmView as BasePasswordResetConfirmView,
                                       PasswordResetCompleteView as BasePasswordResetCompleteView)
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.contrib.auth.views import LoginView as BaseLoginView
from django.core.mail import send_mail
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy

from config import settings
from users.forms import UserForm
from users.models import User


# Create your views here.

class LoginView(BaseLoginView):
    template_name = 'users/login.html'


class LogoutView(BaseLogoutView):
    pass


class RegisterView(CreateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/register.html'

    def form_valid(self, form):

        # создает случайный пароль
        verified_password = ''
        for i in range(8):
            i = randint(0, 9)
            verified_password += str(i)

        # сохраняет пароль к пользователю, чтобы можно было авторизировать его
        form.verified_password = verified_password
        user = form.save(commit=False)
        user.verified_password = verified_password

        # Отправляет письмо на указанную почту со ссылкой. В ссылку встроен пароль для верификации этого пользователя
        send_mail(
            subject='Верификация почты',
            message=f'Если вы регистрировались в Skychimp, нажмите на ссылку: '
                    f'http://127.0.0.1:8000/users/verifying?code={user.verified_password}\n Так вы подтвердите почту',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        return super().form_valid(form)


def verify_view(request):
    code = int(request.GET.get('code'))  # получает код для верификации
    user = User.objects.get(verified_password=code)  # получает пользователя с этим кодом
    user.verified = True  # верифицирует его
    user.save()
    return render(request, 'users/verifying.html')


class PasswordResetView(BasePasswordResetView):
    template_name = 'users/password_reset_form.html'
    email_template_name = 'users/password_reset_email.html'
    from_email = settings.EMAIL_HOST_USER
    success_url = reverse_lazy('users:password_reset_done')


class PasswordResetDoneView(BasePasswordResetDoneView):
    template_name = 'users/password_reset_done.html'


class PasswordResetConfirmView(BasePasswordResetConfirmView):
    template_name = 'users/password_reset_confirm.html'
    success_url = reverse_lazy('users:password_reset_complete')


class PasswordResetCompleteView(BasePasswordResetCompleteView):
    template_name = 'users/password_reset_complete.html'
    success_url = reverse_lazy('users:login')

users/templates/users/login.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Вход</h1>
</div>

<div class="container-fluid">
    <div class="row text-start">
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Заполните поля</h4>

                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Войти</button>
                        <a href="{% url 'users:password_reset' %}" class="btn btn-lg btn-block btn-outline-primary">Забыл пароль</a>
                        <p class="mt-3">
                            <a href="https://t.me/DispatchNotifierBot" target="_blank">Привязать свой аккаунт к Telegram боту</a>
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Пароль успешно изменен</h1>
</div>

<div class="container-fluid">
    <div class="row text-start">
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Вы можете войти под своей почтой и новым паролем</h4>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'mailing/base.html' %}
{% block content %}
  {% if validlink %}
    <h1>Смена пароля</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Подтвердить</button>
    </form>
  {% else %}
    <p>
      Вероятно ссылка неверна или уже была использована
    </p>
  {% endif %}
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Сброс пароля</h1>
</div>

<div class="container-fluid">
    <div class="row text-start">
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Сообщение отправлено</h4>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/password_reset_email.html
Перейдите по ссылке, чтобы изменить пароль.
{{ protocol }}://{{ domain }}{% url "users:password_reset_confirm" uidb64=uid token=token %}
Игнорируйте это сообщение, если вы не хотите менять пароль.

users/templates/users/password_reset_form.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Сброс пароля</h1>
</div>

<div class="container-fluid">
    <div class="row text-start">
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Укажите почту и мы отправим ссылку на восстановление пароля</h4>

                </div>
                <div class="card-body">
                    <form method="post" action="{% url 'users:password_reset' %}" class="form-floating">
                        {{ form }}
                        {% csrf_token %}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить ссылку</button>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/register.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Регистрация</h1>
</div>

<div class="container-fluid">
    <div class="row text-start">
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Заполните поля</h4>

                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Подтвердить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/verifying.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Спасибо за верификацию!</h1>
</div>

<div class="container-fluid">
    <div class="row text-start">
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Теперь ваша почта подтверждена</h4>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}